In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving retail_60000_rows_raw.csv to retail_60000_rows_raw.csv

In [ ]:
df = pd.read_csv("retail_60000_rows_raw.csv")

In [ ]:
df.head()

,order_id,customer_id,order_date,city,category,seller_id,quantity,sales,payment_type,order_status
0,ORD153167,CUST08938,2025-07-25 23:00:00,Mumbai,Books,SELLER_0053,1.0,2283.90,Debit Card,Delivered
1,ORD146547,CUST10661,2025-05-24 01:00:00,Bengaluru,Fashion,SELLER_0071,1.0,3965.17,Debit Card,Delivered
2,ORD134405,CUST12391,2025-12-06 07:00:00,Kochi,Fashion,SELLER_0013,5.0,4027.28,Cash on Delivery,Shipped
3,ORD125414,CUST03601,2025-07-17 19:00:00,Chennai,Grocery,SELLER_0036,3.0,2846.65,Credit Card,Cancelled
4,ORD157277,CUST14688,2025-03-15 08:00:00,Hyderabad,Beauty,SELLER_0066,1.0,4669.87,Debit Card,Delivered

In [ ]:
df.shape

(60300, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60300 entries, 0 to 60299
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      60300 non-null  object
 1   customer_id   60300 non-null  object
 2   order_date    60300 non-null  object
 3   city          58790 non-null  object
 4   category      59091 non-null  object
 5   seller_id     59095 non-null  object
 6   quantity      59393 non-null  float64
 7   sales         59096 non-null  float64
 8   payment_type  58790 non-null  object
 9   order_status  59095 non-null  object
dtypes: float64(2), object(8)
memory usage: 4.6+ MB

In [ ]:
df.isnull().sum()

order_id           0
customer_id        0
order_date         0
city            1510
category        1209
seller_id       1205
quantity         907
sales           1204
payment_type    1510
order_status    1205
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(300)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(60000, 10)

In [ ]:
df.isnull().sum()

order_id           0
customer_id        0
order_date         0
city            1500
category        1200
seller_id       1200
quantity         900
sales           1200
payment_type    1500
order_status    1200
dtype: int64

In [ ]:
categorical_cols = [
    "city",
    "category",
    "seller_id",
    "payment_type",
    "order_status"
]

for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

In [ ]:
numeric_cols = ["quantity", "sales"]

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [ ]:
df.isnull().sum()

order_id        0
customer_id     0
order_date      0
city            0
category        0
seller_id       0
quantity        0
sales           0
payment_type    0
order_status    0
dtype: int64

In [ ]:
df["order_date"] = pd.to_datetime(df["order_date"])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60000 entries, 0 to 60299
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      60000 non-null  object
 1   customer_id   60000 non-null  object
 2   order_date    60000 non-null  datetime64[ns]
 3   city          60000 non-null  object
 4   category      60000 non-null  object
 5   seller_id     60000 non-null  object
 6   quantity      60000 non-null  float64
 7   sales         60000 non-null  float64
 8   payment_type  60000 non-null  object
 9   order_status  60000 non-null  object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 5.0+ MB

In [ ]:
df["year"] = df["order_date"].dt.year

In [ ]:
df["month"] = df["order_date"].dt.month

In [ ]:
df["order_value"] = df["sales"] * df["quantity"]

In [ ]:
df.head()

,order_id,customer_id,order_date,city,category,seller_id,quantity,sales,payment_type,order_status,year,month,order_value
0,ORD153167,CUST08938,2025-07-25 23:00:00,Mumbai,Books,SELLER_0053,1.0,2283.90,Debit Card,Delivered,2025,7,2283.90
1,ORD146547,CUST10661,2025-05-24 01:00:00,Bengaluru,Fashion,SELLER_0071,1.0,3965.17,Debit Card,Delivered,2025,5,3965.17
2,ORD134405,CUST12391,2025-12-06 07:00:00,Kochi,Fashion,SELLER_0013,5.0,4027.28,Cash on Delivery,Shipped,2025,12,20136.40
3,ORD125414,CUST03601,2025-07-17 19:00:00,Chennai,Grocery,SELLER_0036,3.0,2846.65,Credit Card,Cancelled,2025,7,8539.95
4,ORD157277,CUST14688,2025-03-15 08:00:00,Hyderabad,Beauty,SELLER_0066,1.0,4669.87,Debit Card,Delivered,2025,3,4669.87

In [ ]:
df.to_csv("retail_cleaned.csv", index=False)

In [ ]:
import os
os.path.exists("retail_cleaned.csv")

True

In [ ]:
import sqlite3

In [ ]:
conn = sqlite3.connect("retail.db")

In [ ]:
df.to_sql("orders", conn, if_exists="replace", index=False)

60000

In [ ]:
pd.read_sql("SELECT * FROM orders LIMIT 5", conn)

,order_id,customer_id,order_date,city,category,seller_id,quantity,sales,payment_type,order_status,year,month,order_value
0,ORD153167,CUST08938,2025-07-25 23:00:00,Mumbai,Books,SELLER_0053,1.0,2283.90,Debit Card,Delivered,2025,7,2283.90
1,ORD146547,CUST10661,2025-05-24 01:00:00,Bengaluru,Fashion,SELLER_0071,1.0,3965.17,Debit Card,Delivered,2025,5,3965.17
2,ORD134405,CUST12391,2025-12-06 07:00:00,Kochi,Fashion,SELLER_0013,5.0,4027.28,Cash on Delivery,Shipped,2025,12,20136.40
3,ORD125414,CUST03601,2025-07-17 19:00:00,Chennai,Grocery,SELLER_0036,3.0,2846.65,Credit Card,Cancelled,2025,7,8539.95
4,ORD157277,CUST14688,2025-03-15 08:00:00,Hyderabad,Beauty,SELLER_0066,1.0,4669.87,Debit Card,Delivered,2025,3,4669.87

In [ ]:
pd.read_sql("""
SELECT SUM(order_value) AS total_sales
FROM orders
""", conn)

    total_sales
0  4.580761e+08

In [ ]:
pd.read_sql("""
SELECT COUNT(*) AS total_orders
FROM orders
""", conn)

   total_orders
0         60000

In [ ]:
pd.read_sql("""
SELECT category,
       SUM(order_value) AS total_sales
FROM orders
GROUP BY category
ORDER BY total_sales DESC
""", conn)

      category   total_sales
0         Home  6.497343e+07
1      Grocery  6.495845e+07
2       Beauty  6.458977e+07
3      Fashion  6.419572e+07
4  Electronics  6.383899e+07
5        Books  6.333249e+07
6       Sports  6.288151e+07
7      Unknown  9.305712e+06

In [ ]:
pd.read_sql("""
SELECT city,
       SUM(order_value) AS total_sales
FROM orders
GROUP BY city
ORDER BY total_sales DESC
""", conn)

         city   total_sales
0      Mumbai  5.710637e+07
1  Coimbatore  5.674706e+07
2       Kochi  5.626580e+07
3   Hyderabad  5.585216e+07
4     Chennai  5.571693e+07
5   Bengaluru  5.532835e+07
6       Delhi  5.486430e+07
7        Pune  5.472752e+07
8     Unknown  1.146758e+07

In [ ]:
pd.read_sql("""
SELECT seller_id,
       SUM(order_value) AS total_sales
FROM orders
GROUP BY seller_id
ORDER BY total_sales DESC
LIMIT 10
""", conn)

     seller_id  total_sales
0      Unknown  9101572.640
1  SELLER_0082  4982603.210
2  SELLER_0039  4974507.545
3  SELLER_0049  4934282.595
4  SELLER_0005  4923345.075
5  SELLER_0080  4905772.945
6  SELLER_0002  4889877.005
7  SELLER_0043  4886330.540
8  SELLER_0085  4883136.045
9  SELLER_0042  4856729.270

In [ ]:
pd.read_sql("""
SELECT year,
       month,
       SUM(order_value) AS total_sales
FROM orders
GROUP BY year, month
ORDER BY year, month
""", conn)

    year  month   total_sales
0   2025      1  4.010547e+07
1   2025      2  3.564632e+07
2   2025      3  4.018652e+07
3   2025      4  3.777200e+07
4   2025      5  3.760360e+07
5   2025      6  3.773944e+07
6   2025      7  3.917501e+07
7   2025      8  3.839362e+07
8   2025      9  3.702861e+07
9   2025     10  3.854783e+07
10  2025     11  3.804683e+07
11  2025     12  3.783084e+07

In [ ]:
pd.read_sql("""
SELECT order_status,
       COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC
""", conn)

  order_status  total_orders
0    Delivered         33673
1    Cancelled          8436
2     Returned          8364
3      Shipped          8327
4      Unknown          1200

In [ ]:
pd.read_sql("""
SELECT payment_type,
       COUNT(*) AS total_orders,
       SUM(order_value) AS total_sales
FROM orders
GROUP BY payment_type
ORDER BY total_sales DESC
""", conn)

       payment_type  total_orders   total_sales
0  Cash on Delivery         11778  9.045408e+07
1       Credit Card         11694  8.957200e+07
2        Debit Card         11729  8.944002e+07
3       Net Banking         11694  8.908262e+07
4               UPI         11605  8.804760e+07
5           Unknown          1500  1.147975e+07

In [ ]:
conn.close()

In [ ]:
from google.colab import files
files.download("retail_cleaned.csv")